name: Training model
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  package-model:
    
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: [3.7]
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create package
        run: |
          pip install pyyaml
          python setup.py sdist
          export model_name="$(ls dist)"
          echo "dist/$model_name"

      - name: Push package to local-server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.LOCAL_SERVER_SSH }}
          port: ${{ secrets.PORT }}
          source: "dist/$model_name"
          target: "storage/packages"
          strip_components: 1

      - name: Train model on local-server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.LOCAL_SERVER_SSH }}
          port: ${{ secrets.PORT }}
          script: docker run --name test-training -v /home/glegoff/storage/:/storage -e DATA_PATH=storage/data/ -e model_name="$model_name" --rm train-model:latest
