name: Training model
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  

jobs:
  package-model:
    
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: [3.7]
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create package
        run: |
          python setup.py sdist
          ls -l

      - name: Push package to local-server
        uses: appleboy/scp-action@master
        with:
          host: {{ secrets.HOST }}
          username: {{ secrets.USERNAME }}
          password: {{ secrets.LOCAL_SERVER_SSH }}
          port: {{ secrets.PORT }}
          source: trainer-0.1.tar.gz
          target: "storage/packages/"
