name: Deployment Workflow
on:
  push:
    branches: [master]

jobs:
  job_one:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
       - name: test ssh connection
         uses: appleboy/ssh-action@master
         with:
           host: 91.177.176.96
           username: glegoff
           key: ${{ SECRET.SSH_LOCAL_SERVER}}
           port: 22
           script: |
             cd NLP-for-fun
             git clone https://github.com/guillaumelgf/NLP-model-prod.git
             cd NLP-model-prod
             git status
